src/ASPNET_MVC5_DEV_IO.Application/ViewModels/ProdutoViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace ASPNET_MVC5_DEV_IO.Application.ViewModels;

public class ProdutoViewModel
{
    [Key] public Guid Id { get; set; }
    
    [Required(ErrorMessage = "O campo {0} é obrigatório")] 
    [DisplayName("Fornecedor")]
    public Guid FornecedorId { get; set; }
    
    [Required(ErrorMessage = "O campo {0} é obrigatório")]
    [StringLength(200, ErrorMessage = "O campo {0} precisa ter entre {2} e {1} caracteres", MinimumLength = 2)]
    public string Nome { get; set; }
    
    [Required(ErrorMessage = "O campo {0} é obrigatório")]
    [StringLength(1000, ErrorMessage = "O campo {0} precisa ter entre {2} e {1} caracteres", MinimumLength = 2)]
    public string Descricao { get; set; }
    
    [DisplayName("Imagem do Produto")]
    public FormFile ImagemFile { get; set; }
    
    public string Imagem { get; set; }
    
    [Required(ErrorMessage = "O campo {0} é obrigatório")]
    public decimal Valor { get; set; }
    
    [ScaffoldColumn(false)]
    public DateTime Cadastro { get; set; }
    
    [DisplayName("Ativo?")]
    public bool Ativo { get; set; }

    public FornecedorViewModel Fornecedor { get; set; }
    public IEnumerable<FornecedorViewModel> Fornecedores { get; set; }
}

src/ASPNET_MVC5_DEV_IO.Application/Controllers/ProdutosController.cs
using ASP_NET_MVC5_DEV_IO.Business.Core.Notificacoes;
using ASP_NET_MVC5_DEV_IO.Business.Models.Fornecedores.DataAbstraction;
using ASP_NET_MVC5_DEV_IO.Business.Models.Produtos.DataAbstrations;
using ASP_NET_MVC5_DEV_IO.Business.Models.Produtos.Entidades;
using Microsoft.AspNetCore.Mvc;
using ASP_NET_MVC5_DEV_IO.Business.Models.Produtos.Services;
using ASPNET_MVC5_DEV_IO.Application.ViewModels;
using AutoMapper;

namespace ASPNET_MVC5_DEV_IO.Application.Controllers;

public class ProdutosController : BaseController
{
    private readonly IProdutoRepository _produtoRepository;
    private readonly IFornecedorRepository _fornecedorRepository;
    private readonly IProdutoService _produtoService;

    public ProdutosController(
        IFornecedorRepository fornecedorRepository,
        IProdutoRepository produtoRepository,
        IProdutoService produtoService,
        IMapper mapper,
        INotificador notificador) : base(mapper, notificador)
    {
        _produtoService = produtoService;
        _produtoRepository = produtoRepository;
        _fornecedorRepository = fornecedorRepository;
    }

    [Route("lista-de-produtos")]
    [HttpGet]
    public async Task<IActionResult> Index()
    {
        return View(_mapper.Map<IEnumerable<ProdutoViewModel>>(await _produtoRepository.ObterProdutosFornecedores()));
    }

    [Route("editar-produto/{id:guid}")]
    [HttpGet]
    public async Task<IActionResult> Edit(Guid id)
    {
        var produtoViewModel = await ObterProduto(id);

        if (produtoViewModel == null) return NotFound();

        return View(produtoViewModel);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    [Route("editar-produto")]
    public async Task<IActionResult> Edit(ProdutoViewModel produtoViewModel)
    {
        if (!ModelState.IsValid) return View(produtoViewModel);
        
        await _produtoService.Atualizar(_mapper.Map<Produto>(produtoViewModel));
        
        if(!OperacaoValida()) return View(produtoViewModel);
        
        return RedirectToAction("Index");
    }

    [HttpGet]
    [Route("excluir-produto/{id:guid}")]
    public async Task<IActionResult> Delete(Guid id)
    {
        var produtoViewModel = await ObterProduto(id);

        if (produtoViewModel == null) return NotFound();

        return View(produtoViewModel);
    }

    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    [Route("excluir-produto/{id:guid}")]
    public async Task<IActionResult> DeleteConfirmed(Guid id)
    {
        var produtoViewModel = await ObterProduto(id);

        if (produtoViewModel == null)
        {
            return NotFound();
        }

        await _produtoService.Remover(id);
        
        if(!OperacaoValida()) return View(produtoViewModel);
        
        return RedirectToAction("Index");
    }

    [Route("novo-produto")]
    public async Task<IActionResult> Create()
    {
        var produto = new ProdutoViewModel();

        await PopularFornecedores(produto);

        return View(produto);
    }

    [Route("novo-produto")]
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(ProdutoViewModel produtoViewModel)
    {
        await PopularFornecedores(produtoViewModel);

        if (!ModelState.IsValid) return View(produtoViewModel);

        var imgPrefixo = Guid.NewGuid() + "_";
        if (!UploadImagem(produtoViewModel.ImagemFile, imgPrefixo)) return View(produtoViewModel);

        await _produtoRepository.Adicionar(_mapper.Map<Produto>(produtoViewModel));
        
        if(!OperacaoValida()) return View(produtoViewModel);
        
        return RedirectToAction("Index");
    }


    [Route("dados-do-produto/{id:guid}")]
    public async Task<IActionResult> Details(Guid id)
    {
        var produtoViewModel = await ObterProduto(id);

        if (produtoViewModel == null) return NotFound();

        return View(produtoViewModel);
    }

    private async Task<ProdutoViewModel> ObterProduto(Guid id)
    {
        var produto = _mapper.Map<ProdutoViewModel>(await _produtoRepository.ObterProdutoFornecedor(id));

        await PopularFornecedores(produto);

        return produto;
    }

    private async Task PopularFornecedores(ProdutoViewModel produtoViewModel) =>
        produtoViewModel.Fornecedores =
            _mapper.Map<IEnumerable<FornecedorViewModel>>(await _fornecedorRepository.ObterTodos());

    protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            _produtoRepository.Dispose();
            _produtoService.Dispose();
        }

        base.Dispose(disposing);
    }

    private bool UploadImagem(FormFile img, string imgPrefixo)
    {
        if (img == null || img.Length <= 0)
        {
            ModelState.AddModelError(string.Empty, "Imagem em formato inválido");
            return false;
        }

        var path = Path.Combine("~/imagens", imgPrefixo + img.FileName);

        if (System.IO.File.Exists(path))
        {
            ModelState.AddModelError(string.Empty, "Já existe um arquivo com este nome");
        }

        System.IO.File.Create(path);
        return true;
    }
}

src/ASPNET_MVC5_DEV_IO.Application/Views/Produtos/Create.cshtml
@model ASPNET_MVC5_DEV_IO.Application.ViewModels.ProdutoViewModel

@{
    ViewBag.Title = "Cadastro de Fornecedor";
}

<h2>@ViewBag.Title</h2>

<hr/>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <partial name="_ErrorSummary"/>
        
        <div class="form-group">
            @Html.LabelFor(model => model.FornecedorId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">

                @Html.DropDownListFor(model => model.FornecedorId, new SelectList(Model.Fornecedores, "Id", "Nome"),
                    string.Empty, new { @class = "form-control" })

                @Html.ValidationMessageFor(model => model.FornecedorId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.Descricao, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImagemFile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                <input type="file" asp-for="ImagemFile"/>
                <span class="input-group-btn"></span>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ativo, htmlAttributes: new { @class = "controllabel col-md-2" })
            <div class="col-md-3">
                @Html.CheckBoxFor(model => model.Ativo, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-3">
                <input type="submit" value="Cadastrar" class="btn btn-primary"/>
                <a class="btn btn-info" href="@Url.Action("Index", "Produtos")">Voltar</a>
            </div>
        </div>
    </div>
}

@section Scripts
{
    <script>
        $("#Valor").attr("data-val-number", "Moeda em formato inválido."); 
    </script>
}

src/ASPNET_MVC5_DEV_IO.Application/Views/Produtos/Delete.cshtml
@model ASPNET_MVC5_DEV_IO.Application.ViewModels.ProdutoViewModel

@{
    ViewBag.Title = $"Deseja realmente excluir o fornecedor {Model.Nome}?";
}

<h1>@ViewBag.Title</h1>

<hr/>

<div class="row">
    <h4>Esta ação será permanente!</h4>
    <hr/>
    <dl class="row">
        <div>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Nome)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Nome)
            </dd>
        </div>

        <div>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Fornecedor.Nome)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Fornecedor.Nome)
            </dd>
        </div>

        <div>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Ativo)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Ativo)
            </dd>
        </div>
    </dl>

    @using (Html.BeginForm(HttpMethod.Delete))
    {
        @Html.AntiForgeryToken()

        <div class="form-group">
            <input type="submit" value="Excluir" class="btn-danger"/>
            @Html.ActionLink("Voltar", "Index", new { @class = "btn btn-default" })
        </div>
    }
</div>

src/ASPNET_MVC5_DEV_IO.Application/Views/Produtos/Details.cshtml
@model ASPNET_MVC5_DEV_IO.Application.ViewModels.ProdutoViewModel


@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>title</h2>

src/ASPNET_MVC5_DEV_IO.Application/Views/Produtos/Edit.cshtml
@model ASPNET_MVC5_DEV_IO.Application.ViewModels.ProdutoViewModel

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
                    @Html.LabelFor(model => model.FornecedorId, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-3">
                        
                        @Html.DropDownListFor(model => model.FornecedorId, new SelectList(Model.Fornecedores, "Id", "Nome"),
                            string.Empty, new {@class = "form-control"})
                        
                        @Html.ValidationMessageFor(model => model.FornecedorId, "", new { @class = "text-danger" })
                    </div>
                </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-3">
                @Html.EditorFor(model => model.Descricao, "", new {@class = "form-control"})
                @Html.ValidationMessageFor(model => model.Descricao, "", new {@class = "text-danger"})
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.Imagem, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-3">
                
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.Ativo, htmlAttributes: new {@class = "controllabel col-md-2"})
            <div class="col-md-3">
                @Html.CheckBoxFor(model => model.Ativo, htmlAttributes: new {@class = "form-control"})
            </div>
        </div>
 
        <div class="form-group">
            <div class="col-md-offset-2 col-md-3">
                <input type="submit" value="Cadastrar" class="btn btn-primary"/>
                <a class="btn btn-info" href="@Url.Action("Index", "Produtos")">Voltar</a>
            </div>
        </div>
    </div>
}

src/ASPNET_MVC5_DEV_IO.Application/Views/Produtos/Index.cshtml
@model System.Collections.Generic.IEnumerable<ASPNET_MVC5_DEV_IO.Application.ViewModels.ProdutoViewModel>

@{
    ViewBag.Title = "Lista de Produtos";
}

<h1><b>@ViewBag.Title</b></h1>
<hr/>

<p>
    <a class="btn btn-info" href="@Url.Action("Create", "Produtos")">
        Novo Produto
    </a>
</p>

@await  Html.PartialAsync("_ListaProdutos"); 

src/ASPNET_MVC5_DEV_IO.Application/Views/Produtos/_ListaProdutos.cshtml
@model IEnumerable<ASPNET_MVC5_DEV_IO.Application.ViewModels.ProdutoViewModel>

<table class="table-hover table">
    <thead>
    <tr>
        <th>

        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fornecedor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Valor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ativo)
        </th>
        <th>
            
        </th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                <img src="~/images/@item.Imagem" alt="@item.Imagem" style="width: 70px; height: 100px;" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fornecedor)
            </td>
            <td>
                @item.Valor.ToString("C"); 
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ativo)
            </td>
            <td class="text-right">
                <a class="btn btn-warning" href="@Url.Action("Details", "Produtos", new {id = item.Id})"> Detalhes</a>
                <a class="btn btn-info" href="@Url.Action("Edit", "Produtos", new {id = item.Id})"> Editar</a>
                <a class="btn btn-danger" href="@Url.Action("Delete", "Produtos", new {id = item.Id})"> Excluir</a>
            </td>
        </tr>
    }
    </tbody>
</table>